### ISSUE TITLE
[opening issues is hard] soulcore problems

### ISSUE THREAD

**Issue by quat1024** [quat1024/incorporeal#11]
collection of issues people are too lazy to go on github to open

- [x] ender core has 1 tick with no inventory causing problems with corporea sparks
- [x] look in to head syncing
- [ ] get the head back when you break it, that shit is expensive

**Comment by SnazzGass** [comment]
> collection of issues people are too lazy to go on github to open

*hides

**Comment by quat1024** [comment]
Superseded by #17. I fixed the actual bug, head syncing seems to be fine, the third one is addressed in #17
