### ISSUE TITLE
take a break u spaghetti sauce

### ISSUE THREAD

**Issue by quat1024** [quat1024/incorporeal#21]
Quotch youve been working on this mod like constantly and you dont even no what your stuff does anymore, you need to step back and work on your other mods, or like Fuckin Play The Game actually, instead of endlessly modding it Hoyl shit

**Comment by Birgliss** [comment]
quat i'm gonna organize an intervention, don't die in the next 24 hours ok

**Comment by quat1024** [comment]
done
