### ISSUE TITLE
Server-ended crash

### ISSUE THREAD

**Issue by Sunconure11** [quat1024/incorporeal#24]
User of my massive-ass pack is trying to make a server using said pack, and ran into this issue with incorporeal.

https://pastebin.com/z3L7aHJ8

**Comment by quat1024** [comment]
As it turns out I am actually a dumbass

**Comment by quat1024** [comment]
Wow, ok classloading is a lot weirder than I expected it to be...

```java
Minecraft mc = Minecraft.getMinecraft(); //totally fine on server
mc.addScheduledTask(() -> {              //totally fine on server
  World world = mc.world;                //crashes!
}
```

Who knew? Not me.

I also found another instance of bad classloading, that would have crashed if this didn't. Should be fixed when I push the next update in a few minutes.

**Comment by quat1024** [comment]
Now approved @ https://minecraft.curseforge.com/projects/incorporeal/files/2702146

Sorry about that! I need to get back in the habit of testing on servers...

**Comment by quat1024** [comment]
![image](https://user-images.githubusercontent.com/2068021/56484000-4ca37500-649b-11e9-98bf-6f2f11362016.png)
