### ISSUE TITLE
InfraRedstone compatibility module causes crashes in various mods

### ISSUE THREAD

**Issue by svitoos** [quat1024/incorporeal#25]
https://github.com/CharsetMC/Charset/issues/397

RandomThings (when attaching Spectre Coil): https://pastebin.com/2XEWTx2H

**Comment by quat1024** [comment]
what in heck

**Comment by quat1024** [comment]
thanks hubry for helping narrow this down. problematic line is https://github.com/quat1024/incorporeal/blob/fb595b9d296231eb910a8f802b928d12388c3b89/src/main/java/quaternary/incorporeal/compat/infraredstone/InRedAttachCapabilitiesEventHandler.java#L56

too early to call hascapability in the general case

solution: *always* attach the capability to every single tileentity?

**Comment by quat1024** [comment]
thanks for reporting this. attachcapabilitiesevent strikes again. fixed in 1.1.3
