### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Zygus42** [quat1024/incorporeal#30]
New version is crashing on startup.

[crash-2019-08-23_07.22.29-client.txt](https://github.com/quat1024/incorporeal/files/3532250/crash-2019-08-23_07.22.29-client.txt)

Botania+r1.10-361
incorporeal-1.2.1
Baubles-1.12-1.5.2
forge-1.12.2-14.23.5.2838-installer-win

**Comment by quat1024** [comment]
dupe of #29
