### ISSUE TITLE
Crash on startup with 'Tool Progression' 

### ISSUE THREAD

**Issue by ghost** [quat1024/incorporeal#31]
https://paste.dimdev.org/obubebivan.mccrash 

The crash was caused after adding tool progression, but looking at the logs, most of the errors are on your mod's behalf; No other mod is listed as a cause by vanilla fix either (Just incorporeal and tool progression)

**Comment by quat1024** [comment]
Hey, sorry for the radio silence. Working on this.

**Comment by quat1024** [comment]
Fixed in 1.2.3 - check Curse in a few minutes/hours.
