### ISSUE TITLE
The Sweet Alexum doesn't react to tile entity acceleration

### ISSUE THREAD

**Issue by TheDeviantCrafter** [quat1024/incorporeal#33]
Tried using Random Things' time in a bottle to accelerate the Sweet Alexum. To be surprise, this doesn't make the song play really quickly.

It sure would sound disgusting if it were to be played at 50 times normal speed. I need this in my life.

**Comment by quat1024** [comment]
Hmm, yeah, they use the global world time for computing the position in the song, but I could probably switch it to using a per-flower timer. Sounds like a good time

**Comment by quat1024** [comment]
In the mean time, I can attest to petite flowers being placed on Enchanted Soil sounding absolutely horrible.
