### ISSUE TITLE
Placing Ender Soul Core crashed the world

### ISSUE THREAD

**Issue by Kartabass** [quat1024/incorporeal#35]
[crash-report.txt](https://github.com/quat1024/incorporeal/files/3826809/crash-report.txt)

The instant I placed the Ender Soul Core on my player head, the world crashed, as well as every time after when I tried reloading the world. The player head showed the standard Steve texture, instead of my usual player skin at the time.
For some reason, I'm unable to recreate the bug now. So... that's good?

**Comment by quat1024** [comment]
The crash report says you were running incorporeal 1.0.3 which is literally over 1 year old
