### ISSUE TITLE
Rod of The Fractured Space Doesn't Work With Botania Tweaks

### ISSUE THREAD

**Issue by ToAsgaard** [quat1024/incorporeal#37]
Rod of the Fractured Space when bound to an open crate will just keep saying "Missing Crate at Bound Location" when Botania Tweaks is installed.  I tried the past 3 versions of each of the two mods, as well as the beta version of botania tweaks.    Upon removing botania tweaks, the rod will resume working as normal/intended.  Tested in a fresh world with just botania, baubles, incorporeal, and botania tweaks.

**Comment by ToAsgaard** [comment]
Oh and versions may help :p  Just in case they are needed, using MC 1.12, Forge 14.23.5.2854, Botania r1.10-363, Baubles 1.5.2, BotaniaTweaks 1.8.6 (as well as tested others), and Incorporeal 1.2.4 (as well as testing others)

**Comment by quat1024** [comment]
sorry for the radio silence, still thinkin about this just got some other things on my plate rn!

**Comment by quat1024** [comment]
should be fixed in 1.2.5 which i'll upload to curse in a hot minute!

**Comment by ToAsgaard** [comment]
You are the best, thank you a ton!
